In [50]:
using CSV, DataFrames, Gadfly, GLM, Distributions

In [51]:
train = CSV.read("train.csv")
size(train,1)

14094

In [52]:
Y₁ = collect(train[:,:NA_Sales])
Y₂ = collect(train[:,:Global_Sales])

Other = collect(train[:,:Other_Sales])
JP = collect(train[:,:JP_Sales])
X = collect(train[:,:Genre])

for i in eachindex(X) 
    if ismissing(X[i])
        X[i] = "missing"
    end
end

genreSet = Set(X) 
genres = collect(genreSet) 


n = size(Y₁,1)

##Contient toutes les variables qualitatives
X1 = hcat(ones(n))


for i= 1:(length(genres)-1)
    genre = genres[i]
    qualitative = zeros(n)
    if(genre != "missing" && genre != "Platform")
        ## on parcourt tous les element de la variable Rating
        for j in eachindex(X) 
            if X[j] == genre
                qualitative[j] = 1
            end
        end
        X1 = hcat(X1,qualitative)
    end
end


X1 = hcat(X1, Other, JP)

t1=X1[:,2]
t2=X1[:,3]
t3=X1[:,4]
t4=X1[:,5]
t5=X1[:,6]
t6=X1[:,7]
t7=X1[:,8]
t8=X1[:,9]
t9=X1[:,10]
t10=X1[:,11]
t11=X1[:,12]
t12=X1[:,13]
p = size(X1,2)-1


12

In [53]:
# Calculer le VIF
VIF = Float64[] 

for i=1:p

    ind = trues(p+1)
    ind[i+1] = false
    XX = X1[:,ind]
    YY = X1[:,.!(ind)]

    β̂ = (XX'XX)\XX'YY
    e = YY-XX*β̂
    SSE = sum(e.^2)
    SST = sum((YY-mean(YY)).^2)

    R² = 1-SSE/SST

    push!(VIF,1/(1-R²))
    
end

VIF

12-element Array{Float64,1}:
 1.2595317128105374
 1.463230727570387 
 2.0165981481403183
 1.4524054515843208
 1.5565744429425814
 1.7762275199772493
 1.321380295320756 
 1.6087605026416696
 1.2161733927053542
 1.3131795677478153
 1.09325960922473  
 1.1170616146835026

In [54]:
F = eigfact(X1'X1)
λ = F[:values]
ϕ = sqrt.(maximum(λ)./λ)

13-element Array{Float64,1}:
 10.456528726887214 
  5.968275658626333 
  5.592606327731688 
  5.065747061892027 
  4.665086804715119 
  4.330463136365263 
  3.86702701529456  
  3.815229921248141 
  3.4808753115980164
  3.2649497161488465
  2.949629554030694 
  2.491481457773633 
  1.0               

In [ ]:
# Création d'un dataframe pour conserver les R² de tous les modèles 
df1 = DataFrame(Strategy = Int64[],Adventure = Int64[],Action = Int64[], Racing = Int64[], Role_Playing = Int64[],Sports = Int64[],Simulation = Int64[],Misc = Int64[],Puzzle = Int64[],Fighting = Int64[],Other_Sales = Int64[], JP_Sales = Int64[], R2aj = Float64[], R2prev = Float64[])

# Variabilité totale
SST = sum((Y₁ .- mean(Y₁)).^2)
for i1=0:1  
    for i2=0:1 
        for i3=0:1 
            for i4=0:1 
                for i5=0:1 
                    for i6=0:1 
                        for i7=0:1 
                            for i8=0:1 
                                for i9=0:1
                                    for i10=0:1
                                        for i11=0:1
                                            for i12=0:1
        # Construction de la matrice des variables explicatives
        X = ones(n,1)
        if i1==1
            X = hcat(X,t1)
        end
        if i2==1
            X = hcat(X,t2)
        end
        if i3==1
            X = hcat(X,t3)
        end
        if i4==1
            X = hcat(X,t4)
        end
        if i5==1
            X = hcat(X,t5)
        end
        if i6==1
            X = hcat(X,t6)
        end
        if i7==1
            X = hcat(X,t7)
        end
        if i8==1
            X = hcat(X,t8)
        end
        if i9==1
            X = hcat(X,t9)
        end
          
        if i10==1
            X = hcat(X,t10)
        end
                                                
        if i11==1
            X = hcat(X,t11)
        end
    
        if i12==1
            X = hcat(X,t12)
        end
                                                
        # estimation des paramètres
        β̂ = (X'*X)\X'*Y₁
        # Calculs des résidus
        e = Y₁ .- X*β̂
        # Calcul de la matrice H pour la validation croisée
        H = X/(X'*X)*X'
        # Calcul des erreurs de validation croisée
        ẽ = e./(1 .- diag(H))
        # Calcul du coefficient de détermination de prévision
        R̃² = 1-sum(ẽ.^2)/ SST

        # Calcul du coefficient de détermination ajusté
        p = size(X,2)-1
        SSE = sum(e.^2)
        R² =  1 - SSE/SST * (n-1)/(n-p)

        # Stocker les résultats dans le dataframe
        push!(df1,[i1 i2 i3 i4 i5 i6 i7 i8 i9 i10 i11 i12 R² R̃²])
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end
df1

In [ ]:
tail(df1)
describe(df1)
r2 = df1[:R2aj]

indexMax = 2
max = 0
for i in eachindex(r2)
    if(max < r2[i])
        max = r2[i]
        indexMax = i
    end
end

df1[indexMax,:]

In [ ]:
# Création d'un dataframe pour conserver les R² de tous les modèles 
df2 = DataFrame(Strategy = Int64[],Adventure = Int64[],Action = Int64[], Racing = Int64[], Role_Playing = Int64[],Sports = Int64[],Simulation = Int64[],Misc = Int64[],Puzzle = Int64[],Fighting = Int64[],Other_Sales = Int64[], JP_Sales = Int64[], R2aj = Float64[], R2prev = Float64[])

# Variabilité totale
SST = sum((Y₂ .- mean(Y₂)).^2)
for i1=0:1  
    for i2=0:1 
        for i3=0:1 
            for i4=0:1 
                for i5=0:1 
                    for i6=0:1 
                        for i7=0:1 
                            for i8=0:1 
                                for i9=0:1
                                    for i10=0:1
                                        for i11=0:1
                                            for i12=0:1
        # Construction de la matrice des variables explicatives
        X = ones(n,1)
        if i1==1
            X = hcat(X,t1)
        end
        if i2==1
            X = hcat(X,t2)
        end
        if i3==1
            X = hcat(X,t3)
        end
        if i4==1
            X = hcat(X,t4)
        end
        if i5==1
            X = hcat(X,t5)
        end
        if i6==1
            X = hcat(X,t6)
        end
        if i7==1
            X = hcat(X,t7)
        end
        if i8==1
            X = hcat(X,t8)
        end
        if i9==1
            X = hcat(X,t9)
        end
          
        if i10==1
            X = hcat(X,t10)
        end
                                                
        if i11==1
            X = hcat(X,t11)
        end
    
        if i12==1
            X = hcat(X,t12)
        end
                                                
        # estimation des paramètres
        β̂ = (X'*X)\X'*Y₂
        # Calculs des résidus
        e = Y₂ .- X*β̂
        # Calcul de la matrice H pour la validation croisée
        H = X/(X'*X)*X'
        # Calcul des erreurs de validation croisée
        ẽ = e./(1 .- diag(H))
        # Calcul du coefficient de détermination de prévision
        R̃² = 1-sum(ẽ.^2)/ SST

        # Calcul du coefficient de détermination ajusté
        p = size(X,2)-1
        SSE = sum(e.^2)
        R² =  1 - SSE/SST * (n-1)/(n-p)

        # Stocker les résultats dans le dataframe
        push!(df2,[i1 i2 i3 i4 i5 i6 i7 i8 i9 i10 i11 i12 R² R̃²])
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

df2

In [ ]:
tail(df2)
describe(df2)
r2_2 = df2[:R2aj]

indexMax2 = 2
max2 = 0
for i in eachindex(r2_2)
    if(max2 < r2_2[i])
        max2 = r2_2[i]
        indexMax2 = i
    end
end

df2[indexMax2,:]

In [33]:
β̂₁ = (X1'X1)\X1'Y₁

β̂₂ = (X2'X2)\X2'Y₂

3-element Array{Float64,1}:
 0.12340840358458269
 2.2084604101912313 
 5.076323019358454  

In [34]:
test = CSV.read("test.csv")
head(test)

6×13 DataFrame. Omitted printing of 9 columns
│ Row │ ID     │ Platform │ Year_of_Release │ Genre        │
│     │ Int64⍰ │ String⍰  │ Int64⍰          │ String⍰      │
├─────┼────────┼──────────┼─────────────────┼──────────────┤
│ 1   │ 14095  │ GBA      │ 2002            │ Fighting     │
│ 2   │ 14096  │ PS3      │ 2008            │ Action       │
│ 3   │ 14097  │ N64      │ 1997            │ Sports       │
│ 4   │ 14098  │ GC       │ 2002            │ Fighting     │
│ 5   │ 14099  │ X360     │ 2010            │ Role-Playing │
│ 6   │ 14100  │ DS       │ 2009            │ Adventure    │

In [31]:
T₁=test[:,:JP_Sales]
T₂=test[:,:Other_Sales]
T₃=test[:,:Global_Sales]
T₄=test[:,:NA_Sales]
n = length(T₁)
T1 = hcat(ones(n),T₁,T₂,T₃)
T2 = hcat(ones(n),T₁,T₂)

NA_Sales = β̂₁*T1

Global_Sales = β̂₂*T2

predictions = DataFrame(ID = test[:ID], NA_Sales = NA_Sales, Global_Sales = Global_Sales)
CSV.write("predictions.csv",prediction)

┌ Warning: indexing with colon as row will create a copy in the future use df[col_inds] to get the columns without copying
│   caller = top-level scope at In[31]:1
└ @ Core In[31]:1
┌ Warning: indexing with colon as row will create a copy in the future use df[col_inds] to get the columns without copying
│   caller = top-level scope at In[31]:2
└ @ Core In[31]:2
┌ Warning: indexing with colon as row will create a copy in the future use df[col_inds] to get the columns without copying
│   caller = top-level scope at In[31]:3
└ @ Core In[31]:3


KeyError: KeyError: key :Global_Sales not found